export const EXPERIMENT_ALERTS = {
  connectionMode: {
    dedupeKey: 'step-1-connection-mode',
    description: 'Drag nodes from apparatus to complete the circuit connections.',
    icon: '🔌',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Connection Mode Activated',
    type: 'info',
  },
  circuitConnectionsCompleted: {
    description: 'The default wiring path has been placed on the apparatus.',
    icon: '✅',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Circuit Connections Completed Successfully',
    type: 'success',
  },
  incorrectNodeConnection: {
    description: 'One or more wires are connected to the wrong node pair.',
    icon: '❌',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Incorrect Node Connection Detected',
    type: 'error',
  },
  checkingConnections: {
    description: 'The lab console is validating each wire path.',
    duration: 2200,
    icon: '🎛️',
    stepNumber: 2,
    target: '#check-button',
    title: 'Checking Circuit Connections...',
    type: 'info',
  },
  connectionsVerified: {
    description: 'You can now set resistance values and power the circuit.',
    icon: '✅',
    stepNumber: 2,
    target: '#resistance-controls',
    title: 'All Connections Verified Successfully',
    type: 'success',
  },
  connectionErrorFound: {
    icon: '⚠️',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Connection Error Found - Please Recheck Wiring',
    type: 'error',
  },
  adjustResistance: {
    dedupeKey: 'step-3-adjust-resistance',
    description: 'Use the three resistance sliders before starting the supply.',
    icon: '🎛️',
    stepNumber: 3,
    target: '#resistance-controls',
    title: 'Adjust Resistance Values Using Sliders',
    type: 'info',
  },
  resistanceLocked: {
    description: 'Resistance controls are locked while the circuit is powered.',
    icon: '✅',
    stepNumber: 3,
    target: '#resistance-controls',
    title: 'Resistance Values Locked for Experiment',
    type: 'success',
  },
  powerOn: {
    description: 'The supply is now feeding the verified circuit.',
    icon: '⚡',
    stepNumber: 4,
    target: '#power-supply',
    title: 'Power Supply Turned ON',
    type: 'success',
  },
  cannotStartPower: {
    description: 'Run CHECK and correct the circuit wiring before powering the supply.',
    icon: '⚠️',
    stepNumber: 4,
    target: '#check-button',
    title: 'Cannot Start Power - Complete Connections First',
    type: 'warning',
  },
  adjustVoltage: {
    dedupeKey: 'step-5-adjust-voltage',
    description: 'Move the voltage control and watch the meter needles respond.',
    icon: '⚡',
    stepNumber: 5,
    target: '#voltage-control',
    title: 'Adjust Voltage to Observe Ammeter Readings',
    type: 'info',
  },
  currentUpdating: {
    dedupeKey: 'step-5-current-updating',
    description: 'The ammeter values are linked to the active supply voltage.',
    duration: 2600,
    icon: '📊',
    stepNumber: 5,
    target: '#equipment-panel',
    title: 'Current Readings Updating in Real Time',
    type: 'info',
  },
  voltageSafetyLimit: {
    dedupeKey: 'step-5-voltage-safety-limit',
    description: 'Reduce the setting if the readings become unstable.',
    duration: 5200,
    icon: '⚠️',
    stepNumber: 5,
    target: '#voltage-control',
    title: 'Voltage Approaching Safety Limit',
    type: 'warning',
  },
  addingReading: {
    description: 'The current values are being transferred to the table.',
    duration: 1800,
    icon: '📊',
    stepNumber: 6,
    target: '#observation-table-panel',
    title: 'Adding Current Readings to Observation Table',
    type: 'info',
  },
  readingAdded: {
    description: 'The observation row has been stored.',
    icon: '✅',
    stepNumber: 6,
    target: '#observation-table-panel',
    title: 'Reading Added Successfully',
    type: 'success',
  },
  readingAlreadyExists: {
    description: 'Change the voltage before recording another observation.',
    icon: '⚠️',
    stepNumber: 6,
    target: '#voltage-control',
    title: 'Reading Already Exists',
    type: 'warning',
  },
  continueReadings: {
    description: 'Record readings at different voltage settings before plotting.',
    icon: '📊',
    stepNumber: 7,
    target: '#add-reading-button',
    title: 'Continue Taking Readings Until Minimum 6 Entries',
    type: 'info',
  },
  minimumReadingsRequired: {
    icon: '⚠️',
    stepNumber: 7,
    target: '#observation-table-panel',
    title: 'Minimum 6 Readings Required for Graph Plotting',
    type: 'warning',
  },
  sufficientData: {
    description: 'The graph and report controls are ready to use.',
    icon: '✅',
    stepNumber: 7,
    target: '#plot-button',
    title: 'Sufficient Data Collected for Graph',
    type: 'success',
  },
  comparingValues: {
    description: 'The console is comparing measured branch currents with expected values.',
    duration: 2200,
    icon: '📊',
    stepNumber: 8,
    target: '#observation-table-panel',
    title: 'Comparing Practical and Theoretical Values',
    type: 'info',
  },
  kclVerified: {
    description: 'The total current equals the sum of branch currents within tolerance.',
    icon: '✅',
    stepNumber: 8,
    target: '#observation-table-panel',
    title: "Kirchhoff's Current Law Verified Successfully",
    type: 'success',
  },
  valuesDeviate: {
    description: 'Check wiring, resistance values, and recorded readings before continuing.',
    icon: '⚠️',
    stepNumber: 8,
    target: '#observation-table-panel',
    title: 'Observed Values Deviate from Expected Results',
    type: 'warning',
  },
  generatingGraph: {
    description: 'The graph panel is preparing current-versus-voltage traces.',
    duration: 1900,
    icon: '📊',
    stepNumber: 9,
    target: '#graph-panel',
    title: 'Generating Experimental Graph...',
    type: 'info',
  },
  graphPlotted: {
    description: 'The recorded observations are now plotted.',
    icon: '✅',
    stepNumber: 9,
    target: '#graph-panel',
    title: 'Graph Plotted Successfully',
    type: 'success',
  },
  insufficientGraphReadings: {
    icon: '❌',
    stepNumber: 9,
    target: '#observation-table-panel',
    title: 'Insufficient Readings to Plot Graph',
    type: 'error',
  },
  preparingReport: {
    description: 'The print view is being prepared from the current observations.',
    duration: 2000,
    icon: '📊',
    stepNumber: 10,
    target: '#print-button',
    title: 'Preparing Experiment Report for Printing',
    type: 'info',
  },
  printLayoutGenerated: {
    description: 'The print dialog will use the generated experiment layout.',
    icon: '✅',
    stepNumber: 10,
    target: '#print-button',
    title: 'Print Layout Generated Successfully',
    type: 'success',
  },
  resettingSetup: {
    description: 'The lab system is returning controls to their initial state.',
    duration: 1800,
    icon: '🎛️',
    stepNumber: 11,
    target: '#reset-button',
    title: 'Resetting Experiment Setup...',
    type: 'info',
  },
  resetWarning: {
    confirmLabel: 'OK',
    dedupeKey: 'step-11-reset-warning',
    description: 'Confirm reset before the current table and circuit are cleared.',
    icon: '⚠️',
    placement: 'center',
    requiresConfirmation: true,
    stepNumber: 11,
    target: '#reset-button',
    title: 'All Readings and Connections Will Be Cleared',
    type: 'warning',
  },
  resetSuccess: {
    description: 'The apparatus is ready for a fresh run.',
    icon: '✅',
    stepNumber: 11,
    target: '#circuit-panel',
    title: 'Experiment Reset Successfully',
    type: 'success',
  },
}
